name: pgx-kg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.31.0
  - pandas>=2.0.0
  - pyyaml>=6.0
  - pytest>=7.4.0
  - notebook
  - pip
  - pip:
    - rdflib>=7.0.0
    - Jinja2>=3.1.2
    - retry>=0.9.2
    - streamlit>=1.28.0
    - reportlab>=4.0.0
    - Pillow>=10.0.0
    - plotly>=5.17.0
    - qrcode>=7.4.0

