name: pgx-clinical-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core dependencies
    - streamlit>=1.28.0
    - pandas>=2.0.0
    - pyyaml>=6.0
    - requests>=2.31.0
    - retry>=0.9.2
    
    # RDF and data modeling
    - rdflib>=7.0.0
    - jinja2>=3.1.2
    
    # Dashboard visualization
    - plotly>=5.17.0
    - reportlab>=4.0.0
    - Pillow>=10.0.0
    - qrcode>=7.4.0
    
    # AI photo generation (optional)
    # Use latest version for best Imagen model support
    - google-genai>=0.7.0
    
    # Testing and development
    - pytest>=7.4.0
    - notebook>=7.0.0

