[theme]
primaryColor = "#1E64C8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true
# Disable file watcher to prevent "inotify watch limit reached" errors
fileWatcherType = "none"

[browser]
gatherUsageStats = false

