# Copy-safe template for local development only
# Never commit real secrets. On Streamlit Cloud, set these in App → Settings → Secrets.

[api_keys]
# NCBI (optional, used for certain data fetches)
ncbi_email = "momenmohamed82@gmail.com"
ncbi_api_key = "3934c59d1d6aa604d6598791001974cd6c08"

# BioPortal (used by DynamicClinicalGenerator)
bioportal_api_key = "753b30b6-30e0-42c5-9a31-d39d62dcd209"

# Google AI Studio / Gemini (Imagen 3). Used by AIPhotoGenerator when service="gemini"
GOOGLE_API_KEY = "AIzaSyBDdhwMut-AB0vcZp7POiV8hJslAr1wtdg"

# OpenAI (kept for compatibility if you switch services)
OPENAI_API_KEY = "your-openai-api-key"

# Stability AI (kept for compatibility if you switch services)
STABILITY_API_KEY = "your-stability-api-key"


# Top-level duplicates for convenience (so st.secrets["KEY"] also works)
GOOGLE_API_KEY = "AIzaSyBDdhwMut-AB0vcZp7POiV8hJslAr1wtdg"
OPENAI_API_KEY = "your-openai-api-key"
STABILITY_API_KEY = "your-stability-api-key"
ncbi_email = "your-email@example.com"
ncbi_api_key = "your-ncbi-api-key"
bioportal_api_key = "your-bioportal-api-key"


